# Generated by Django 5.1.1 on 2024-10-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_canteen_faculty_product_stall_delete_moodentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='image',
            field=models.CharField(default='fisipmakara.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.CharField(default='fisipmakara.png', max_length=100),
            preserve_default=False,
        ),
    ]
