# Generated by Django 5.1.1 on 2024-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_canteen_image_faculty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='price',
            field=models.CharField(default='Rp10.000–Rp25.000/pax', max_length=120),
            preserve_default=False,
        ),
    ]
