# Generated by Django 5.1.1 on 2024-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faculty_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name_css_class',
            field=models.CharField(default='mb-4 rounded-full py-0.5 px-2.5 border border-transparent text-xs text-white transition-all shadow-sm w-20 text-center bg-gradient-to-r from-cyan-600 to-black', max_length=200),
            preserve_default=False,
        ),
    ]
