# Generated by Django 5.1.1 on 2024-10-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faculty_name_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='cuisine',
            field=models.CharField(choices=[('indonesian', 'Indonesian'), ('chinese', 'Chinese'), ('western', 'Western'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('others', 'Others'), ('indian', 'Indian'), ('beverages', 'Beverages')], default='others', max_length=50),
        ),
    ]
