# Generated by Django 5.1.1 on 2024-10-27 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stall',
            name='cuisine',
            field=models.CharField(choices=[('indonesian', 'Indonesian'), ('chinese', 'Chinese'), ('western', 'Western'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('indian', 'Indian'), ('beverages', 'Beverages'), ('dessert', 'Dessert'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
