# Generated by Django 5.1.1 on 2024-12-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_favoriteproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='name_css_class',
            new_name='colors',
        ),
    ]
